### ISSUE TITLE
Gå direkte til betalingsmetode i widgeten

### ISSUE THREAD

**Issue by Mofoss** [stiftelsen-effekt/effekt-widget#36]
Når man klikker på Vipps, PayPal eller bank på gieffektivt.no så åpnes widgeten, der førstesider er at man skal velge betalingsmetode. Kan vi hoppe over det steget, sånn at man kommer direkte til Vipps hvis man klikker på Vipps?

Jeg vet ikke hvordan det funker, men i dag er linken:
javascript: window.widget.show();

Kunne det vært type?
javascript: window.widget.show(method=bank);

Hvis dette er enkelt (typ bare å endre linkene), så er det supert. Hvis ikke kan dette heller legges på backlogen (ikke så viktig).

**Comment by fellmirr** [comment]
```widget.setMethod("BANK");
    widget.goToSlide(1);
    widget.show();```

Tilsvarende med VIPPS og PAYPAL

:)

Kanskje @joulebit kunne fiksa det?

Blir en litt artig animasjon når man åpner den, men no big deal tenker jeg.

**Comment by Mofoss** [comment]
Jeg testet naivt bare å erstatte dagens lenke på objektene (`javascript: widget.show();`) med :
`javascript: widget.setMethod(BANK); widget.goToSlide(1); widget.show();`

Det fungerte ikke. @joulebit, om du forstår hvordan man får dette til så er det supert! Test gjerne på www.gieffektivt.no/dialogisk siden den siden ikke har noen trafikk (i tilfelle feil eller besøk samtidig med testing)

**Comment by fellmirr** [comment]
Trikset ser ut til å være å bruke en såkalt Immediately Invoked Function Expression i lenken.

```javascript: (function() {widget.setMethod("BANK");widget.goToSlide(1);widget.show();})()```

https://developer.mozilla.org/en-US/docs/Glossary/IIFE

Jeg forstod ikke helt hvor linkene var definert i Tilda @Mofoss , men kanskje du har styring?

**Comment by Mofoss** [comment]
@fellmirr, jeg har prøvd nå, men jeg fikk det ikke til å fungere. Widgeten vises ikke. Jeg forsøkte også å sette .show først for å se om jeg kunne se at widgeten først og så at den byttet bilde, men kan ikke se at noe skjer (men da vises iaf widgeten). 

Hvis du vil forsøke selv, så er linkene inne i bildene (symbolene) inne i Block Editor på Tilda. De er litt vanskelige å finne, men gå på Tilda > Dialogisk-siden > den delen med betalingslogoene > Block Editor > klikk på f.eks. Vipps > klikk på "Settings" helt nede i høyre hjørne (godt skjult) > finn der i menyen det står "Link" > endre URL'en. 

Alternativt (eller som et tillegg, på utvalgte sider), som diskutert med @AndreasII, så kanskje vi kunne vist widgeten direkte når man åpner en side, uten at man må klikke på en link? Det kan da umulig være så vanskelig å få til at javascriptet til å kjøre umiddelbart. Tipper det tar deg <30 sek tenking å finne ut, men jeg er jo verdens mest udugelige webutvikler så jeg fikk ikke til når jeg prøvde litt nå :-P

**Comment by fellmirr** [comment]
Ja, dette tar nok rundt 30 sekunder å ordne, jeg kan se på dette i helga :) 




Sent from Outlook Mobile







On Wed, May 13, 2020 at 7:51 PM +0200, "Eirik Mofoss" <notifications@github.com> wrote:
















@fellmirr, jeg har prøvd nå, men jeg fikk det ikke til å fungere. Widgeten vises ikke. Jeg forsøkte også å sette .show først for å se om jeg kunne se at widgeten først og så at den byttet bilde, men kan ikke se at noe skjer (men da vises iaf widgeten).



Hvis du vil forsøke selv, så er linkene inne i bildene (symbolene) inne i Block Editor på Tilda. De er litt vanskelige å finne, men gå på Tilda > Dialogisk-siden > den delen med betalingslogoene > Block Editor > klikk på f.eks. Vipps > klikk på "Settings" helt nede i høyre hjørne (godt skjult) > finn der i menyen det står "Link" > endre URL'en.



Alternativt (eller som et tillegg, på utvalgte sider), som diskutert med @AndreasII, så kanskje vi kunne vist widgeten direkte når man åpner en side, uten at man må klikke på en link? Det kan da umulig være så vanskelig å få til at javascriptet til å kjøre umiddelbart. Tipper det tar deg <30 sek tenking å finne ut, men jeg er jo verdens mest udugelige webutvikler så jeg fikk ikke til når jeg prøvde litt nå :-P

**Comment by Mofoss** [comment]
Denne er satt som "Done" nå, og jeg mener jeg så at den også ble merget med koden. Men funksjonaliteten fungerer ikke på nettsiden enda. Er det noe som gjenstår før den "slås på", eller var det bare ikke mulig? :) 

Dette hadde vært spesielt kult å ha samtidig som vi lanserer den nye Vipps-funksjonen, om vi får mange til å gå inn og teste den.
